export const StudentList = [
    {
      ATT_IDEtudiant: "3152",
      ATT_IDInscription: "17924",
      ATT_Nomprenom: "AHL TAKROUR Mohiddin",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "28322785",
      ATT_Email: "mohieddine225@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "49",
      ATT_Stage_cycle_1: 0,
      Att_Stage_cycle_2: 0,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3186",
      ATT_IDInscription: "17785",
      ATT_Nomprenom: "BALTI Khouloud",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "29856828",
      ATT_Email: "khouloudbalti.123@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "55",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3072",
      ATT_IDInscription: "17788",
      ATT_Nomprenom: "BEN ZINEB Narcisse",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "24460746",
      ATT_Email: "narcissesammouda@hotmail.fr",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "86",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3097",
      ATT_IDInscription: "17853",
      ATT_Nomprenom: "CHEIKH-ROUHOU Farah",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "52976549",
      ATT_Email: "cheikhrouhoufarah@yahoo.fr",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "31",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3085",
      ATT_IDInscription: "17920",
      ATT_Nomprenom: "CHOK Yasmine",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "20466660",
      ATT_Email: "yasmine_chok@yahoo.fr",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "36",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3168",
      ATT_IDInscription: "17923",
      ATT_Nomprenom: "DOUCOURE Fousseyni",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "56275373",
      ATT_Email: "doucourefousseyni49@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "81",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3088",
      ATT_IDInscription: "17921",
      ATT_Nomprenom: "FOURATI Malek",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "50621747",
      ATT_Email: "malek.fourati@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "23",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "2962",
      ATT_IDInscription: "17791",
      ATT_Nomprenom: "GOSSA Syrine",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "20333128",
      ATT_Email: "syrinegossa0@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "28",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3101",
      ATT_IDInscription: "17919",
      ATT_Nomprenom: "GUEDICHE Mahmoud",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "28028129",
      ATT_Email: "mahmoudant@hotmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "22",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3210",
      ATT_IDInscription: "17925",
      ATT_Nomprenom: "KANGA Grace Esther",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "52306762",
      ATT_Email: "kangagraceesther@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "27",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3267",
      ATT_IDInscription: "17880",
      ATT_Nomprenom: "KOMBAS Taha Islem",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "55289127",
      ATT_Email: "islemkombas@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "14",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3059",
      ATT_IDInscription: "17799",
      ATT_Nomprenom: "LOUKIL Nour",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "24332324",
      ATT_Email: "nourloukil@icloud.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "23",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3007",
      ATT_IDInscription: "17918",
      ATT_Nomprenom: "MAATOUG Moez",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "53689116",
      ATT_Email: "whatevaman17@hotmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "8",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3083",
      ATT_IDInscription: "17568",
      ATT_Nomprenom: "MESSAOUD Omayma Lara Kawther",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "95487380",
      ATT_Email: "oumaymamesssaoud@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "34",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3440",
      ATT_IDInscription: "17938",
      ATT_Nomprenom: "NOUAARI Feriel",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "52210872",
      ATT_Email: "feriel.nouaari@utctunisie.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "20",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3060",
      ATT_IDInscription: "17803",
      ATT_Nomprenom: "TOUIL Farah",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "54961666",
      ATT_Email: "farahtouil98@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "2",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3127",
      ATT_IDInscription: "17804",
      ATT_Nomprenom: "YAHMADI Mohamed",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "95602188",
      ATT_Email: "mohamedyahmadi@outlook.fr",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "65",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
    {
      ATT_IDEtudiant: "3100",
      ATT_IDInscription: "17922",
      ATT_Nomprenom: "ZARROUK Cyrine",
      ATT_Filiere: "Dipl�me National d'Architecte",
      ATT_AnneeUniversitaire: "2021-2022",
      ATT_Tel: "",
      ATT_Portable: "26299166",
      ATT_Email: "zarroukcyrine@gmail.com",
      ATT_LibClasse: "Architecture",
      ATT_Comptage_1: "49",
      ATT_Stage_cycle_1: 1,
      Att_Stage_cycle_2: 1,
      ATT_image:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png",
    },
  ];
  